name: Go

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        cache-dependency-path: './backend/go.mod'
        go-version: 1.16

    - name: Build
      working-directory: ./backend
      run: go build -v ./...

    - name: Test
      working-directory: ./backend
      run: |
        export GOPATH="$HOME/go/"
        export PATH=$PATH:$GOPATH/bin
        go install github.com/golang/mock/mockgen@v1.6.0
        go install github.com/jstemmer/go-junit-report@latest
        go generate ./...
        go test -v ./... | go-junit-report -set-exit-code > report.xml

    - name: Report
      uses: test-summary/action@v1
      with:
        paths: ./backend/report.xml
      if: always()
